// Application tables are added here in Phase 2 (Track A).
// Better Auth owns `auth.schema.ts` — it is regenerated by `pnpm auth:schema`
// and must not be hand-edited.
export * from './auth.schema';
