import { relations } from 'drizzle-orm';
import {
	char,
	date,
	index,
	integer,
	jsonb,
	numeric,
	pgTable,
	serial,
	text,
	timestamp
} from 'drizzle-orm/pg-core';
import { user } from './auth.schema';

/**
 * Diseases are rows rather than an enum so adding a third is a data change,
 * not a migration plus a code sweep.
 */
export const diseases = pgTable('diseases', {
	id: serial('id').primaryKey(),
	slug: text('slug').notNull().unique(),
	name: text('name').notNull(),
	scientificName: text('scientific_name'),
	sortOrder: integer('sort_order').notNull().default(0)
});

/**
 * County reference table, loaded from `scripts/data/counties.csv` (generated by
 * `pnpm build:geo` from the Census cartographic boundary files). `lon`/`lat` are
 * interior points, not true centroids, so the map's flyTo always lands inside the
 * county it is targeting.
 *
 * No geometry lives here — polygons are a static TopoJSON asset joined in the
 * browser by FIPS. See CLAUDE.md.
 */
export const counties = pgTable(
	'counties',
	{
		fips: char('fips', { length: 5 }).primaryKey(),
		name: text('name').notNull(),
		stateFips: char('state_fips', { length: 2 }).notNull(),
		stateUsps: char('state_usps', { length: 2 }).notNull(),
		stateName: text('state_name').notNull(),
		lon: numeric('lon', { precision: 9, scale: 5, mode: 'number' }).notNull(),
		lat: numeric('lat', { precision: 8, scale: 5, mode: 'number' }).notNull()
	},
	(t) => [index('counties_state_usps_idx').on(t.stateUsps), index('counties_name_idx').on(t.name)]
);

/**
 * A confirmed detection.
 *
 * `crop`, `operationType`, and `strain` are deliberately free text with no lookup
 * tables or constraints — nothing in the map's symbology or filtering reads them,
 * and the vocabularies are genuinely fuzzy. They are normalized on input instead.
 *
 * Rows are soft-deleted so retractions stay auditable. Every query feeding the
 * public map must filter `deletedAt is null`.
 */
export const incidents = pgTable(
	'incidents',
	{
		id: serial('id').primaryKey(),
		diseaseId: integer('disease_id')
			.notNull()
			.references(() => diseases.id),
		countyFips: char('county_fips', { length: 5 })
			.notNull()
			.references(() => counties.fips),

		observedOn: date('observed_on').notNull(),
		reportedOn: date('reported_on'),

		crop: text('crop'),
		operationType: text('operation_type'),
		strain: text('strain'),
		comments: text('comments'),
		source: text('source'),

		// Reserved for possible future point-level precision. Plain numerics — the app
		// has no spatial predicates and deliberately does not depend on PostGIS.
		latitude: numeric('latitude', { precision: 8, scale: 5, mode: 'number' }),
		longitude: numeric('longitude', { precision: 9, scale: 5, mode: 'number' }),

		createdBy: text('created_by').references(() => user.id, { onDelete: 'set null' }),
		createdAt: timestamp('created_at').notNull().defaultNow(),
		updatedAt: timestamp('updated_at')
			.notNull()
			.defaultNow()
			.$onUpdate(() => new Date()),
		deletedAt: timestamp('deleted_at')
	},
	(t) => [
		index('incidents_disease_observed_idx').on(t.diseaseId, t.observedOn),
		index('incidents_county_disease_idx').on(t.countyFips, t.diseaseId),
		index('incidents_observed_on_idx').on(t.observedOn)
	]
);

/**
 * Provenance for hand-curated extension data: who changed what, and to what.
 */
export const auditLog = pgTable(
	'audit_log',
	{
		id: serial('id').primaryKey(),
		actorId: text('actor_id').references(() => user.id, { onDelete: 'set null' }),
		tableName: text('table_name').notNull(),
		rowId: text('row_id').notNull(),
		action: text('action').notNull(),
		before: jsonb('before'),
		after: jsonb('after'),
		createdAt: timestamp('created_at').notNull().defaultNow()
	},
	(t) => [index('audit_log_table_row_idx').on(t.tableName, t.rowId)]
);

export const diseasesRelations = relations(diseases, ({ many }) => ({
	incidents: many(incidents)
}));

export const countiesRelations = relations(counties, ({ many }) => ({
	incidents: many(incidents)
}));

export const incidentsRelations = relations(incidents, ({ one }) => ({
	disease: one(diseases, { fields: [incidents.diseaseId], references: [diseases.id] }),
	county: one(counties, { fields: [incidents.countyFips], references: [counties.fips] }),
	createdByUser: one(user, { fields: [incidents.createdBy], references: [user.id] })
}));

// Better Auth owns `auth.schema.ts` — it is regenerated by `pnpm auth:schema`
// and must not be hand-edited.
export * from './auth.schema';
